var _util=require('util')
var _shipping={
	addAddress:function(data,success,error){
		_util.request({
			method:'post',
			url:'/shipping',
			data:data,
			success:success,
			error:error
		})
	},
	getShippingList:function(success,error){
		_util.request({
			url:'/shipping/list',
			success:success,
			error:error
		})
	},
	deleteShipping:function(data,success,error){
		_util.request({
			method:'put',
			url:'/shipping/delete',
			data:data,
			success:success,
			error:error
		})
	},
	editShippingList:function(data,success,error){
		_util.request({
			url:'/shipping/edit',
			data:data,
			success:success,
			error:error
		})
	},
	editShipping:function(data,success,error){
		_util.request({
			url:'/shipping',
			method:'put',
			data:data,
			success:success,
			error:error
		})
	}
}
module.exports=_shipping