var _util=require('util')
var _order={
	getProductList:function(success,error){
		console.log('aa')
		_util.request({
			url:'/order',
			success:success,
			error:error
		})
	},
	createOrder:function(data,success,error){
		_util.request({
			method:'post',
			url:'/order',
			data:data,
			success:success,
			error:error
		})
	},
	getOrderList:function(page,success,error){
		_util.request({
			url:'/order/list',
			data:page,
			success:success,
			error:error
		})
	},
	getOrderDetail:function(data,success,error){
		_util.request({
			url:'/order/detail',
			data:data,
			success:success,
			error:error
		})
	},
	cancelOrder:function(data,success,error){
		_util.request({
			url:'/order/cancel',
			method:'put',
			data:data,
			success:success,
			error:error
		})
	}
}
module.exports=_order